disabled_rules:
 - identifier_name
 - function_parameter_count
 - opening_brace
 - cyclomatic_complexity
 - function_body_length
line_length: 140
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods